/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "webtoon.h"


void
webtoon_prog_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *init_1_arg;
	int  *result_2;
	compte  inscription_1_arg;
	int  *result_3;
	compte  maj_info_1_arg;
	listSerie  *result_4;
	argTri  afficher_serie_1_arg;
	int  *result_5;
	argAchaSerie  acheter_serie_1_arg;
	int  *result_6;
	argAjouterNote  ajouter_note_1_arg;
	int  *result_7;
	argAchaCoin  acheter_coin_1_arg;
	int  *result_8;
	compte  afficher_coin_1_arg;
	int  *result_9;
	argAchaSerie  ajouter_favoris_1_arg;
	listSerie  *result_10;
	compte  afficher_favoris_1_arg;
	int  *result_11;
	argAchaSerie  supprimer_favoris_1_arg;
	int  *result_12;
	argAjoutComm  ajouter_commentaire_1_arg;
	int  *result_13;
	argAjoutComm  supprimer_commentaire_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, WEBTOON_PROG, WEBTOON_VERSION_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = init_1((void*)&init_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = inscription_1(&inscription_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = maj_info_1(&maj_info_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = afficher_serie_1(&afficher_serie_1_arg, clnt);
	if (result_4 == (listSerie *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = acheter_serie_1(&acheter_serie_1_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = ajouter_note_1(&ajouter_note_1_arg, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = acheter_coin_1(&acheter_coin_1_arg, clnt);
	if (result_7 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = afficher_coin_1(&afficher_coin_1_arg, clnt);
	if (result_8 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = ajouter_favoris_1(&ajouter_favoris_1_arg, clnt);
	if (result_9 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_10 = afficher_favoris_1(&afficher_favoris_1_arg, clnt);
	if (result_10 == (listSerie *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_11 = supprimer_favoris_1(&supprimer_favoris_1_arg, clnt);
	if (result_11 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_12 = ajouter_commentaire_1(&ajouter_commentaire_1_arg, clnt);
	if (result_12 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_13 = supprimer_commentaire_1(&supprimer_commentaire_1_arg, clnt);
	if (result_13 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	webtoon_prog_1 (host);
exit (0);
}
