/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "webtoon.h"

static struct compte tabCompte[10];
static int nbCompte = 0;
static struct serie tabSerie[10];

void *
init_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	struct serie s1;
	strcpy(s1.titre, "Le Hero");
	s1.noteMoyenne;
	s1.listGenre[0]=1;s1.listGenre[1]=3;
	s1.dateSerie.jour=10; s1.dateSerie.mois=1; s1.dateSerie.annee=2020;
	strcpy(s1.listComm[0].comm,"Sympa"); strcpy(s1.listComm[0].pseudo,"Le Narrateur"); 
	strcpy(s1.listComm[1].comm,"Bof deja vu"); strcpy(s1.listComm[1].pseudo,"Malcaor"); 
	s1.nbrVue=10;
	s1.nbEpisode=3;
	strcpy(s1.description, "Une aventure");

	struct serie s2;
	strcpy(s2.titre, "L'enfermation");
	s2.noteMoyenne;
	s2.listGenre[0]=1;s2.listGenre[1]=2;
	s2.dateSerie.jour=10; s2.dateSerie.mois=1; s2.dateSerie.annee=2020;
	strcpy(s2.listComm[0].comm,"lol"); strcpy(s2.listComm[0].pseudo,"Le Narrateur"); 
	strcpy(s2.listComm[1].comm,"Je pleurais"); strcpy(s2.listComm[1].pseudo,"Malcaor"); 
	s2.nbrVue=10;
	s2.nbEpisode=3;
	strcpy(s2.description, "Cela fait 3 mois, ma famille s'inquiete, je mange du pain rassis, la police ne viens toujours pas. A l'aide.\n");

	return (void *) &result;
}

int *
inscription_1_svc(compte *argp, struct svc_req *rqstp)
{
	static int  result;
	struct serie s[15];
	struct compte *c = (struct compte *) malloc(sizeof(struct compte));
	strcpy(c->pseudo, argp->pseudo);
	strcpy(c->mdp,argp->mdp);
	if(argp->carteBancaire>0){
		c->carteBancaire = argp->carteBancaire;		
	}
	c->coin = argp->coin;
	
	tabCompte[nbCompte] = *c;
	if(&tabCompte[nbCompte] != NULL){result=1;nbCompte++;}else{result=0;}
	
	return &result;
}

int *
maj_info_1_svc(compte *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

listSerie *
afficher_serie_1_svc(argTri *argp, struct svc_req *rqstp)
{
	static listSerie  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
acheter_serie_1_svc(argAchaSerie *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
ajouter_note_1_svc(argAjouterNote *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
acheter_coin_1_svc(argAchaCoin *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
afficher_coin_1_svc(compte *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
ajouter_favoris_1_svc(argAchaSerie *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

listSerie *
afficher_favoris_1_svc(compte *argp, struct svc_req *rqstp)
{
	static listSerie  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
supprimer_favoris_1_svc(argAchaSerie *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
ajouter_commentaire_1_svc(argAjoutComm *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
supprimer_commentaire_1_svc(argAjoutComm *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
